services:

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-net1
  nginx:
    image: nginx:latest
    networks:
      - my-net1
    restart: always
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
networks:
  my-net1:
    driver: bridge
